<?php

namespace App\Console\Commands;

use App\Models\FacultyMembers;
use Illuminate\Console\Command;
use App\Models\FacultyMember;

class InsertFacultyMembers extends Command
{
    protected $signature = 'insert:faculty';
    protected $description = 'Insert faculty members into the database';

    public function handle()
    {
        $this->info('Inserting faculty members...');

        $departmentMap = [
            'علوم الحاسب' => 'CS',
            'نظم المعلومات' => 'IS',
            'تكنولوجيا المعلومات' => 'IT',
            'دعم القرار' => 'DS',
        ];

        $facultyMembers = [
            ['name_ar' => 'إبراهيم محمود محمد الحناوى', 'name_en' => 'Ibrahim Mahmoud Mohamed El-Hanawy', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'أحمد رأفت عباس محمد', 'name_en' => 'Ahmed Raafat Abbas Mohamed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'إبراهيم حامد إسماعيل رضوان', 'name_en' => 'Ibrahim Hamed Ismail Radwan', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'احمد سامى محمد عبدالسلام', 'name_en' => 'Ahmed Samy Mohamed Abdelsalam', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أحمد صلاح محمد مصطفى', 'name_en' => 'Ahmed Salah Mohamed Mostafa', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'أحمد عبدالستار الهادى مصطفى', 'name_en' => 'Ahmed Abdelsttar El-Hady Mostafa', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أسامه محمد عبدالسلام احمد', 'name_en' => 'Osama Mohamed Abdelsalam Ahmed', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'اسلام سامى محمد عبد السلام', 'name_en' => 'Islam Samy Mohamed Abdelsalam', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أسماء حنفى على غنيمى', 'name_en' => 'Asmaa Hanafy Ali Ghoneimy', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أسماء ناجى حامد عبدالعزيز', 'name_en' => 'Asmaa Nagy Hamed Abdelaziz', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'ايمان احمد حسين سمور', 'name_en' => 'Iman Ahmed Hussein Samour', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'ايمان سمير حسن سيد', 'name_en' => 'Iman Samir Hassan Sayed', 'department' => 'دعم القرار'],
            ['name_ar' => 'أيمن راشد محمد فكرى', 'name_en' => 'Ayman Rasheed Mohamed Fekry', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'إيهاب رشدى محمد عطيه', 'name_en' => 'Ehab Rushdy Mohamed Attia', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'احمد محمد سلطان محمد', 'name_en' => 'Ahmed Mohamed Sultan Mohamed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أمانى صلاح الدين عبدالعزيز', 'name_en' => 'Amany Salah El-Din Abdelaziz', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'أيمن محمد مصطفى حسانين', 'name_en' => 'Ayman Mohamed Mostafa Hassanein', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'جواهر سليمان حسين محمد', 'name_en' => 'Gawhar Soliman Hussein Mohamed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'خالد عبدالسلام على عبدالسلام', 'name_en' => 'Khaled Abdelsalam Ali Abdelsalam', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'خالد على الدرندلى محمد سعيد الدرندلى', 'name_en' => 'Khaled Ali El-Dardndly Mohamed Saeed El-Dardndly', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'خالد محمد حسنى محمد', 'name_en' => 'Khaled Mohamed Hassany Mohamed', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'زاهر عوض ابوالعنين الهندى', 'name_en' => 'Zaher Awad Abou El-Enein El-Hendy', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'سارة محمد شوقى محمد خليفة', 'name_en' => 'Sarah Mohamed Shawky Mohamed Khalifa', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'سعاد محمد نجيب محمد', 'name_en' => 'Soad Mohamed Naguib Mohamed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'شرين زكى ابراهيم سليمان', 'name_en' => 'Sherin Zaki Ibrahim Soliman', 'department' => 'دعم القرار'],
            ['name_ar' => 'الشيماء عادل طنطاوى عبده', 'name_en' => 'El-Shaimaa Adel Tantawy Abdo', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'شيماء محمد محمود محمد', 'name_en' => 'Shaimaa Mohamed Mahmoud Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'عبدالمنعم فؤاد مصطفى عبدالله', 'name_en' => 'Abdelmoneim Fouad Mostafa Abdallah', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'عبدالناصر حسين رياض زايد', 'name_en' => 'AbdelNasser Hussein Riad Zayed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'عصام سليمان يوسف محمد ضبيع', 'name_en' => 'Essam Soliman Youssef Mohamed Dabee', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'عمرو ابراهيم احمد عرجاوى', 'name_en' => 'Amr Ibrahim Ahmed Ergawey', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'كرم محمد جودة محمد سلام', 'name_en' => 'Karim Mohamed Gouda Mohamed Salam', 'department' => 'دعم القرار'],
            ['name_ar' => 'لمياء سليم محمد فتحى سليم فايد', 'name_en' => 'Lamyaa Saleem Mohamed Fathy Saleem Fayad', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'محمد سعيد امام محمد', 'name_en' => 'Mohamed Saeed Imam Mohamed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'محمد علاء فهمى حسانين الغمرى', 'name_en' => 'Mohamed Alaa Fahmy Hassanein El-Ghomry', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'محمد منير حسن محمد حسن', 'name_en' => 'Mohamed Mounir Hassan Mohamed Hassan', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'محمود عبدالمعطى حسن على', 'name_en' => 'Mahmoud Abdelmottaleb Hassan Ali', 'department' => 'دعم القرار'],
            ['name_ar' => 'محمود محمد إسماعيل على', 'name_en' => 'Mahmoud Mohamed Ismail Ali', 'department' => 'دعم القرار'],
            ['name_ar' => 'مروة محمد عبداللاة محمود ابو العزم', 'name_en' => 'Marwa Mohamed Abdellah Mahmoud Abou El-Azm', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'مروة محمود عبد اللطيف خشبة', 'name_en' => 'Marwa Mahmoud Abdel Latif Khashba', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'منى جمال محمد مرسى', 'name_en' => 'Mona Gamal Mohamed Morsi', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'مى محمد عباس مرسى شومان', 'name_en' => 'Mai Mohamed Abbas Morsi Shoman', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'نبيل على محمد علي لاشين', 'name_en' => 'Nabil Ali Mohamed Ali Lasheen', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'نبيل مصطفى عبد العزيز على', 'name_en' => 'Nabil Mostafa Abdel Aziz Ali', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'نسرين عبدالغفار سليمان الصابر', 'name_en' => 'Nasreen Abdel Ghaffar Soliman El-Saber', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'نهى محمد ابراهيم محمد حمزة', 'name_en' => 'Noha Mohamed Ibrahim Mohamed Hamza', 'department' => 'دعم القرار'],
            ['name_ar' => 'نورا زكى عبدالفتاح حسنين', 'name_en' => 'Nora Zaki Abdel Fattah Hassanein', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'هبة زكى محمد عبدالله الفقى', 'name_en' => 'Heba Zaki Mohamed Abdallah El-Feky', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'هناء محمد حمزة كمال', 'name_en' => 'Hanaa Mohamed Hamza Kamal', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'هيام محمد عبدالسلام محمد', 'name_en' => 'Heyam Mohamed Abdelsalam Mohamed', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'وائل سعيد عبدالمجيد محمد', 'name_en' => 'Wael Saeed Abdel Meguid Mohamed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'وفاء توفيق عبد المنعم', 'name_en' => 'Wafaa Tawfik Abdel Moneim', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'وليد ابراهيم ابراهيم خضر', 'name_en' => 'Waleed Ibrahim Ibrahim Khodr', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'زينات محمد أحمد محمد', 'name_en' => 'Zenat Mohamed Ahmed Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'سماح عبدالرحمن عبدالعزيز السيد', 'name_en' => 'Samah Abdel Rahman Abdel Aziz El-Sayed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'سارة عبدالرازق أحمد عبدالحميد', 'name_en' => 'Sarah Abdel Razek Ahmed Abdel Hameed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'سمر لطفي عبدالعزيز الحاوي', 'name_en' => 'Samar Lotfy Abdel Aziz El-Hawi', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'إسماعيل محمد إسماعيل على', 'name_en' => 'Ismail Mohamed Ismail Ali', 'department' => 'دعم القرار'],
            ['name_ar' => 'ياسمين محمد محمد خضر', 'name_en' => 'Yasmine Mohamed Mohamed Khodr', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'سهام عبدالقادر عبدالحميد حسين', 'name_en' => 'Seham Abdel Kader Abdel Hameed Hussein', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أميرة محمد فوزي عبدالفتاح', 'name_en' => 'Amira Mohamed Fawzy Abdel Fattah', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'دعاء سعد عبدالحميد حسن الشوره', 'name_en' => 'Doaa Saad Abdel Hameed Hassan El-Shoura', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'شيماء صابر سعيد قطب محمد', 'name_en' => 'Shaimaa Saber Saeed Kotb Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'ولاء محمد الهادي كمال عبدالعزيز', 'name_en' => 'Walaa Mohamed El-Hady Kamal Abdel Aziz', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'أسماء محمد خالد محمد عباس', 'name_en' => 'Asmaa Mohamed Khaled Mohamed Abbas', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'مصطفى خميس الباز رمضان', 'name_en' => 'Mostafa Khamis El-Baz Ramadan', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'دعاء الشحات بركات محمد', 'name_en' => 'Doaa El-Shahat Barakat Mohamed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'سارة السيد سليمان خليل', 'name_en' => 'Sarah El-Sayed Soliman Khalil', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'صفا السعيد محمد عبدالكريم', 'name_en' => 'Safa El-Saeed Mohamed Abdel Karim', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أسماء عبدالقادر عبدالقادر محمود', 'name_en' => 'Asmaa Abdel Kader Abdel Kader Mahmoud', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'ليلى عبدالفتاح شوقى إبراهيم', 'name_en' => 'Laila Abdel Fattah Shawky Ibrahim', 'department' => 'دعم القرار'],
            ['name_ar' => 'الزهراء محمود إبراهيم على عبدالله', 'name_en' => 'El-Zahraa Mahmoud Ibrahim Ali Abdallah', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'حسناء رأفت حامد سليمان', 'name_en' => 'Hassanaa Raafat Hamed Soliman', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'هبه رشاد إسماعيل على عبدالهادي', 'name_en' => 'Heba Rashad Ismail Ali Abdel Hady', 'department' => 'دعم القرار'],
            ['name_ar' => 'سماح إبراهيم عبدالعال عبدالرحيم', 'name_en' => 'Samah Ibrahim Abdel Aal Abdel Rahim', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أحمد محمود محمود داود', 'name_en' => 'Ahmed Mahmoud Mahmoud Dawood', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'محمد ماهر عبدالحفيظ السيد حسن', 'name_en' => 'Mohamed Maher Abdel Hafez El-Sayed Hassan', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أمير السيد جوده حسن فوده', 'name_en' => 'Amir El-Sayed Gouda Hassan Fouda', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'صابر محمد السيد السيد', 'name_en' => 'Saber Mohamed El-Sayed El-Sayed', 'department' => 'دعم القرار'],
            ['name_ar' => 'أحمد محمود عبدالمعطى حسين', 'name_en' => 'Ahmed Mahmoud Abdel Mottaleb Hussein', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'نشوى السيد اسماعيل احمد', 'name_en' => 'Nashwa El-Sayed Ismail Ahmed', 'department' => 'دعم القرار'],
            ['name_ar' => 'عبدالواحد ابراهيم محمود خميس', 'name_en' => 'Abdel Wahed Ibrahim Mahmoud Khamis', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'مي محمد عبدالستار جعفر', 'name_en' => 'Mai Mohamed Abdel Sattar Gafar', 'department' => 'دعم القرار'],
            ['name_ar' => 'عمرو محمد عبداللطيف امام', 'name_en' => 'Amr Mohamed Abdel Latif Imam', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'حسن عباس حسن عبدالباري', 'name_en' => 'Hassan Abbas Hassan Abdel Bary', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'حفصة احمد مجدي محمد اسماعيل', 'name_en' => 'Hafsa Ahmed Magdy Mohamed Ismail', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'محمود محمد المهدي كمال محمد', 'name_en' => 'Mahmoud Mohamed El-Mahdy Kamal Mohamed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'هيثم احمد جمال عبدالناصر', 'name_en' => 'Heitham Ahmed Gamal Abdel Nasser', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'إسراء عبدالغفار سالم محمد', 'name_en' => 'Esraa Abdel Ghaffar Salem Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'محمد عبدالباسط متولي عطيه', 'name_en' => 'Mohamed Abdel Baset Metwally Attia', 'department' => 'دعم القرار'],
            ['name_ar' => 'محمود عبدالمنعم مهدي عبدالرحمن', 'name_en' => 'Mahmoud Abdel Moneim Mahdy Abdel Rahman', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'أسماء أحمد حامد خليل', 'name_en' => 'Asmaa Ahmed Hamed Khalil', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'أسماء عاطف حسن السيد', 'name_en' => 'Asmaa Atef Hassan El-Sayed', 'department' => 'دعم القرار'],
            ['name_ar' => 'هبه مصطفى أحمد على خاطر', 'name_en' => 'Heba Mostafa Ahmed Ali Khater', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'أحمد محمد الرفاعى محمد نصير', 'name_en' => 'Ahmed Mohamed El-Refaay Mohamed Naseer', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'محمود حسن محمد حسن النامولى', 'name_en' => 'Mahmoud Hassan Mohamed Hassan El-Namoly', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'عبدالله جمال عبدالله محمود', 'name_en' => 'Abdullah Gamal Abdullah Mahmoud', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'إيمان سليم محمود أحمد محمد شلبي', 'name_en' => 'Iman Saleem Mahmoud Ahmed Mohamed Shelby', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'سلوي السيد أحمد محمود وهيبة', 'name_en' => 'Salwa El-Sayed Ahmed Mahmoud Wahba', 'department' => 'دعم القرار'],
            ['name_ar' => 'شروق الامير محمد عطيه الشاذلي', 'name_en' => 'Shorouk El-Ameer Mohamed Attia El-Shazly', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'ميرنا مجدي محمد حلمي الفخراني', 'name_en' => 'Mirna Magdy Mohamed Helmy El-Fakhrany', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'غادة سعيد زكي محمد عطيه', 'name_en' => 'Ghada Saeed Zaki Mohamed Attia', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'رحاب محمد احمد محمد عرجاوى', 'name_en' => 'Rehab Mohamed Ahmed Mohamed Ergawey', 'department' => 'دعم القرار'],
            ['name_ar' => 'هبه محسن محمد منصور', 'name_en' => 'Heba Mohsen Mohamed Mansour', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'حسام رضا محمد عبدالمجيد هواش', 'name_en' => 'Hossam Reda Mohamed Abdel Meguid Hawash', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'ريهام مدحت محمد خليل', 'name_en' => 'Riham Medhat Mohamed Khalil', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'حسن حسن محمد محمد', 'name_en' => 'Hassan Hassan Mohamed Mohamed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'امل مجدي عبدالمولي محمد علي', 'name_en' => 'Amal Magdy Abdel Mowla Mohamed Ali', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'رضا محمد رمضان احمد رمضان', 'name_en' => 'Reda Mohamed Ramadan Ahmed Ramadan', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'اسراء كمال حسين محمد', 'name_en' => 'Esraa Kamal Hussein Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'اية سلامة عبدالعزيز عبداللطيف', 'name_en' => 'Aya Salama Abdel Aziz Abdel Latif', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'عمرو محمد عبدالعال ابراهيم', 'name_en' => 'Amr Mohamed Abdel Aal Ibrahim', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'محمد امين محمد ذكي صالح', 'name_en' => 'Mohamed Ameen Mohamed Zaki Saleh', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'وفاء احمد محمود صالح', 'name_en' => 'Wafaa Ahmed Mahmoud Saleh', 'department' => 'دعم القرار'],
            ['name_ar' => 'ساميه حسن رمضان رمضان', 'name_en' => 'Samia Hassan Ramadan Ramadan', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'امل فاروق عبدالجواد بدوى', 'name_en' => 'Amal Farouk Abdel Gawad Badawy', 'department' => 'دعم القرار'],
            ['name_ar' => 'احمد محمد احمد علي عبدالمنعم', 'name_en' => 'Ahmed Mohamed Ahmed Ali Abdel Moneim', 'department' => 'دعم القرار'],
            ['name_ar' => 'وليد عبدالله ابراهيم محمود', 'name_en' => 'Waleed Abdullah Ibrahim Mahmoud', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'احمد مجدي متولي معوض الصرصار', 'name_en' => 'Ahmed Magdy Metwally Mowaad El-Sersar', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'محمود ابراهيم محمد احمد', 'name_en' => 'Mahmoud Ibrahim Mohamed Ahmed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'مصطفى احمد حسن احمد خليفه', 'name_en' => 'Mostafa Ahmed Hassan Ahmed Khalifa', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'احمد يحيى عبدالحفيظ علي الصعيدي', 'name_en' => 'Ahmed Yahya Abdel Hafez Ali El-Saidi', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'سهيله ناصر عبداللطيف السيد محمد', 'name_en' => 'Sohaila Nasser Abdel Latif El-Sayed Mohamed', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'محمود محمد ابراهيم محمد', 'name_en' => 'Mahmoud Mohamed Ibrahim Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'محمد جمال سليمان يونس عبدالهادى', 'name_en' => 'Mohamed Gamal Soliman Younes Abdel Hady', 'department' => 'دعم القرار'],
            ['name_ar' => 'احمد ابراهيم محمد عوض عميره', 'name_en' => 'Ahmed Ibrahim Mohamed Awad Omara', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'احمد صلاح عبدالمطلب اسماعيل', 'name_en' => 'Ahmed Salah Abdel Motalleb Ismail', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'عبدالرحمن فتحي عبدالرحمن علي صومع', 'name_en' => 'Abdel Rahman Fathy Abdel Rahman Ali Somaa', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'كريم احمد فاروق شبل محمود', 'name_en' => 'Karim Ahmed Farouk Shebl Mahmoud', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'محمد عماد عبدالسميع محمد', 'name_en' => 'Mohamed Emad Abdel Samea Mohamed', 'department' => 'دعم القرار'],
            ['name_ar' => 'محمد صلاح الدين محمود صباح', 'name_en' => 'Mohamed Salah El-Din Mahmoud Sabah', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'احمد حسام سلامه درويش الحداد', 'name_en' => 'Ahmed Hossam Salama Darwish El-Hadad', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'بسمه خالد علي الدرندلي محمد سعيد', 'name_en' => 'Basma Khaled Ali El-Dardndly Mohamed Saeed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'شيماء مجدي عبدالمنعم محمد محمد بنديري', 'name_en' => 'Shaimaa Magdy Abdel Moneim Mohamed Mohamed Bendary', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'ريهام حسن محمد محمد حسن', 'name_en' => 'Riham Hassan Mohamed Mohamed Hassan', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'علياء احمد علي احمد محمد سليمان', 'name_en' => 'Aliaa Ahmed Ali Ahmed Mohamed Soliman', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'محمد السيد محمد حسن حسن', 'name_en' => 'Mohamed El-Sayed Mohamed Hassan Hassan', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'الاء محمود محمد المر', 'name_en' => 'Alaa Mahmoud Mohamed El-Morr', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'خلود محسن عبدالمجيد مصلحي عابدين', 'name_en' => 'Kholoud Mohsen Abdel Megid Meselhy Abdeen', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'دينا عاطف سالم محمد', 'name_en' => 'Dina Atef Salem Mohamed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'دينا محمد اسماعيل عبدالحميد اسماعيل', 'name_en' => 'Dina Mohamed Ismail Abdel Hameed Ismail', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'ساره طارق محمد محمد الحلبي', 'name_en' => 'Sarah Tarek Mohamed Mohamed El-Helby', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'ندي ناجي لطفي عبدالجواد السيد', 'name_en' => 'Nady Naji Lotfy Abdel Gawad El-Sayed', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'احمد صالح فتوح صالح الصياد', 'name_en' => 'Ahmed Saleh Fetouh Saleh El-Sayad', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'هاجر رمضان مصطفى احمد', 'name_en' => 'Hagar Ramadan Mostafa Ahmed', 'department' => 'تكنولوجيا المعلومات'],
            ['name_ar' => 'اسراء ابراهيم نبيل ابراهيم الدسوقى', 'name_en' => 'Esraa Ibrahim Nabil Ibrahim El-Dessouky', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'مي السيد الشحات السيد', 'name_en' => 'Mai El-Sayed El-Shahat El-Sayed', 'department' => 'دعم القرار'],
            ['name_ar' => 'شروق اسامه حسن عبدالعزيز السيد', 'name_en' => 'Shorouk Osama Hassan Abdel Aziz El-Sayed', 'department' => 'علوم الحاسب'],
            ['name_ar' => 'شوقي السيد عبدالواحد السيد عبدالحميد', 'name_en' => 'Shawky El-Sayed Abdel Wahed El-Sayed Abdel Hameed', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'عمرو محمد ابوالفتوح حسن شحاته', 'name_en' => 'Amr Mohamed Abou El-Fotouh Hassan Shehata', 'department' => 'نظم المعلومات'],
            ['name_ar' => 'ياسمينا السيد احمد ابوعامر سلام', 'name_en' => 'Yasmina El-Sayed Ahmed Abou Amer Salam', 'department' => 'نظم المعلومات']
        ];

        foreach ($facultyMembers as $member) {
            FacultyMembers::create([
                'name_ar' => $member['name_ar'],
                'name_en' => $member['name_en'],
                'department' => $departmentMap[$member['department']] ?? null,
            ]);
        }

        $this->info('Faculty members inserted successfully!');
    }
}
